linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - paralleltest
    - scopelint

issues:
  exclude-use-default: false

linters-settings:
  govet:
    check-shadowing: true

run:
  skip-dirs:
    - example
