name: "CI"

on:
  pull_request:
  push:

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: unit-test
        run: make test
      - name: ci
        run: make ci
